name: Preview multiple PRs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Check out destination repository
      uses: actions/checkout@v3

    - name: Sync PR
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        ./sync_mult_prs.sh
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
