name: PR Preview

on:
  push:
    branches:
      - preview/**
      - preview-cloud/**
      - preview-operator/**
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Check out destination repository
      uses: actions/checkout@v3

    - name: Sync PR
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        ./sync.sh
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
